import Head from "next/head";
import Welcome from "./Welcome";
import Widget from "./Widget";
import Todo from "./Todo";

import { Exo_2 } from 'next/font/google'
const font = Exo_2({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"/>
        <link rel="icon" href="/favicon.ico" />
        <link rel="manifest" href="/manifest.webmanifest" />
      </Head>
      
      <main className={font.className}>
        <div className="container">
          <Todo/>
          <div className="blocks">
            <div className="box">
              <Welcome/>
              <Widget/>
            </div>
            <div className="watermark">
              <span>By LamP</span>
              <div className="line"></div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
